version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
    - method: pip
      path: backend/python
    - requirements: docs/requirements.txt

sphinx:
  fail_on_warning: true
