# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

name: "Run build command in the build environment"
description: "Run build command in the build environment Docker container"

inputs:
  run:
    description: "Command to run in the docker container"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build docker image as the build environment
      uses: ./.github/actions/build-docker

    - name: Run command in the Docker container
      uses: ./.github/actions/run-docker
      with:
        run: ${{ inputs.run }}
