# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

name: "Build and publish the distributions"
description: "Build and publish using the Makefile"

inputs:
  channel:
    description: "Channel to build the distribution for"
    required: true
  dockerToken:
    description: "Token for the docker registry"
    required: true
  cloudflareToken:
    description: "Token for the Cloudflare"
    required: true
  dockerUsername:
    description: "Username for the docker registry"
    required: false
    default: "rapidstream"
  cloudflareAccountID:
    description: "Account for the Cloudflare"
    required: false
    default: "848de03c597aa02475ca2f171acc9905"
  cloudflarePagesProjectName:
    description: "Project name of the Cloudflare Pages"
    required: false
    default: "rapidstream"
  cloudflareR2BucketName:
    description: "Bucket name for the Cloudflare R2"
    required: false
    default: "rapidstream-releases"

runs:
  using: "composite"
  steps:
    - name: Build docker image to use Cloudflare Wrangler
      uses: ./.github/actions/build-docker
      with:
        imageTag: "rapidstream/cloudflare:latest"
        dockerfile: "./buildutils/Dockerfile.cloudflare"

    - name: Publish the installer to Cloudflare Pages
      uses: ./.github/actions/run-docker
      with:
        image: "rapidstream/cloudflare:latest"
        run: >
          retry -- wrangler pages deploy \
            --project-name ${{ inputs.cloudflarePagesProjectName }} \
            buildutils/installer
        dockerOptions: >-
          -e CLOUDFLARE_API_TOKEN=${{ inputs.cloudflareToken }}
          -e CLOUDFLARE_ACCOUNT_ID=${{ inputs.cloudflareAccountID }}

    - name: Clean the workspace
      run: make clean
      shell: bash

    - name: Build the all distribution targets
      run: make DIST_CHANNEL=${{ inputs.channel }} dist-all -j
      shell: bash

    - name: Upload the distribution files to Cloudflare R2
      uses: ./.github/actions/run-docker
      with:
        image: "rapidstream/cloudflare:latest"
        run: |
          bucket="${{ inputs.cloudflareR2BucketName }}"
          channel="${{ inputs.channel }}"
          cd dist/portable
          for file in *.tar.gz; do
            retry -- wrangler r2 object put \$bucket/\$file --file=\$file
            retry -- wrangler r2 object put \$bucket/rapidstream-tapa-\$channel-latest.tar.gz --file=\$file
          done
          cd ../deb
          for file in *.deb; do
            retry -- wrangler r2 object put \$bucket/\$file --file=\$file
            retry -- wrangler r2 object put \$bucket/rapidstream-tapa-\$channel-latest.deb --file=\$file
          done
          cd ../rpm
          for file in *.rpm; do
            retry -- wrangler r2 object put \$bucket/\$file --file=\$file
            retry -- wrangler r2 object put \$bucket/rapidstream-tapa-\$channel-latest.rpm --file=\$file
          done
          cd ../appimage
          for file in *.AppImage; do
            retry -- wrangler r2 object put \$bucket/\$file --file=\$file
            retry -- wrangler r2 object put \$bucket/rapidstream-tapa-\$channel-latest.AppImage --file=\$file
          done
        dockerOptions: >-
          -e CLOUDFLARE_API_TOKEN=${{ inputs.cloudflareToken }}
          -e CLOUDFLARE_ACCOUNT_ID=${{ inputs.cloudflareAccountID }}

    - name: Login to the docker registry
      run: docker login -u ${{ inputs.dockerUsername }} -p ${{ inputs.dockerToken }}
      shell: bash

    - name: Publish the docker image
      run: make DIST_CHANNEL=${{ inputs.channel }} publish-docker
      shell: bash

    - name: Logout from the docker registry
      run: docker logout
      shell: bash
