name: CI

on:
  push:
    branches-ignore:
      - "**/docs?"
  pull_request:
    branches-ignore:
      - "**/docs?"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
      - name: Checkout myself
        uses: actions/checkout@v1
      - name: Restore timestamp for patched clang files
        run: |
          for file in backend/clang/*; do
            touch "${file}" \
              --date="$(git log --max-count=1 --pretty=format:%cD -- "${file}")"
          done
      - name: Install dependencies
        run: |
          ./.github/scripts/install-build-deps.sh
          ./.github/scripts/setup-github-hosted.sh
      - name: Configure myself
        run: cmake -S . -B build
      - name: Cache llvm-src
        uses: actions/cache@v1
        with:
          path: build/_deps/llvm-src
          key: ${{ matrix.os }}-llvm-src-202206-2
      - name: Cache llvm-build
        uses: actions/cache@v1
        with:
          path: build/_deps/llvm-build
          key: ${{ matrix.os }}-llvm-build-202206-2
      - name: Cache llvm-subbuild
        uses: actions/cache@v1
        with:
          path: build/_deps/llvm-subbuild
          key: ${{ matrix.os }}-llvm-subbuild-202206-2
      - name: Build myself
        run: cmake --build build --target all
      - name: Test myself
        run: cmake --build build --target test

  cosim:
    if: github.event_name == 'push' && github.repository == 'UCLA-VAST/tapa'

    runs-on:
      - self-hosted
      - Linux
      - xilinx-tools

    strategy:
      matrix:
        xocl-platform:
          - xilinx_u250_xdma_201830_2
        xocl-version:
          - "2020.2"
          - "2021.1"
          - "2021.2"
        include:
          # Test different tool versions
          - xocl-platform: xilinx_u250_xdma_201830_2
          # Test a platform that does not support floorplanning yet
          - xocl-platform: xilinx_u200_xdma_201830_2
            xocl-version: "2021.2"
          # Vitis 2022.1 requires this platform
          - xocl-platform: xilinx_u250_gen3x16_xdma_4_1_202210_1
            xocl-version: "2022.1"

    env:
      XILINX_HLS: /opt/tools/xilinx/Vitis_HLS/${{ matrix.xocl-version }}
      XILINX_VITIS: /opt/tools/xilinx/Vitis/${{ matrix.xocl-version }}
      XILINX_VIVADO: /opt/tools/xilinx/Vivado/${{ matrix.xocl-version }}

    steps:
      - name: Checkout myself
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          .github/scripts/install-build-deps.sh
          .github/scripts/setup-self-hosted.sh
          python3 -m pip install --upgrade build
          python3 -m build backend/python
          python3 -m pip install backend/python/dist/*.whl

          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            xilinx-u200-xdma-dev \
            xilinx-u250-xdma-dev \
            xilinx-u250-gen3x16-xdma-4.1-202210-1-dev \

      - name: Configure myself
        run: cmake -S . -B build -D PLATFORM=${{ matrix.xocl-platform }}
      - name: Build myself
        run: cmake --build build --target all --parallel $(nproc)
      - name: Test myself
        working-directory: build
        run: |
          source ${XILINX_VITIS}/settings64.sh
          /usr/local/bin/ctest --verbose --parallel $(nproc)
