name: lint

on:
  - push
  - pull_request

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout myself
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          curl --location --output /tmp/clang-format \
            https://github.com/muttleyxd/clang-tools-static-binaries/releases/download/master-208096c1/clang-format-14_linux-amd64
          install /tmp/clang-format /usr/local/bin/clang-format
          rm /tmp/clang-format
      - name: Check format
        run: |
          ./format.sh
          git diff --quiet
