# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

name: Nightly Jobs

on:
  schedule:
    - cron: "8 9 * * *" # 09:08 UTC / 23:08 UTC-10 / 02:08 PDT / 01:08 PST
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout myself
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags.

      - name: Bump version
        run: |
          .github/scripts/bump-version.sh
          git push
        env:
          # Using UTC-10 to generate date so the new version includes all
          # commits from that date for most US timezones.
          TZ: Pacific/Honolulu
