name: package

on:
  push:
    tags:
      - "*"

jobs:
  package-deb:
    if: github.repository == 'Blaok/tapa'

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
      max-parallel: 1

    steps:
      - name: Checkout myself
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          sudo apt-get purge -y libgcc-*-dev || true
          sudo apt-get install -y build-essential python3-pip libboost-coroutine-dev libgflags-dev libgoogle-glog-dev
          sudo apt-get install -y libboost-stacktrace-dev || true
          sudo apt-get autoremove -y
          sudo -H python3 -m pip install --upgrade pip==20.3.4
          sudo -H python3 -m pip install cmake
          wget -O - https://raw.githubusercontent.com/Blaok/fpga-runtime/master/install.sh | bash
      - name: Configure myself
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
      - name: Cache llvm-src
        uses: actions/cache@v1
        with:
          path: build/_deps/llvm-src
          key: ${{ matrix.os }}-llvm-src
      - name: Cache llvm-build
        uses: actions/cache@v1
        with:
          path: build/_deps/llvm-build
          key: ${{ matrix.os }}-llvm-build
      - name: Cache llvm-subbuild
        uses: actions/cache@v1
        with:
          path: build/_deps/llvm-subbuild
          key: ${{ matrix.os }}-llvm-subbuild
      - name: Package myself
        run: cmake --build build --target package
      - name: Cache APT database
        uses: actions/cache@v1
        with:
          path: apt-db-cache
          key: ${{ runner.os }}-apt-db-cache
      - name: Update APT repository
        run: ./.github/scripts/upload-apt-repo.sh
        env:
          BUILD_DIR: build
          CACHE_DIR: apt-db-cache
          LABEL: Extending High-Level Synthesis for Task-Parallel Programs
          GPG_KEY: ${{ secrets.GPG_KEY }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

  package-pypi:
    if: github.repository == 'Blaok/tapa'

    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install setuptools and wheel
        run: pip install --upgrade setuptools wheel
      - name: Checkout myself
        uses: actions/checkout@v2
      - name: Install myself
        working-directory: backend/python
        run: python setup.py install
      - name: Build dist
        working-directory: backend/python
        run: python setup.py sdist bdist_wheel
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          packages_dir: backend/python/dist/
