# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

name: Staging Build

concurrency:
  group: release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Staging Build
    runs-on: self-hosted

    steps:
      - name: Checkout myself
        uses: actions/checkout@v4

      - name: Run bazel
        uses: ./.github/actions/run-command
        with:
          run: |
            mkdir -p /workspace/artifacts.out/
            bazel build --config=release //:tapa-pkg-tar
            cp -L bazel-bin/tapa-pkg-tar.tar /workspace/artifacts.out/tapa.tar
        env:
          UBUNTU_PRO_TOKEN: ${{ secrets.UBUNTU_PRO_TOKEN }}
          MAC_ADDRESS: ${{ secrets.MAC_ADDRESS }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tapa
          path: ${{ github.workspace }}/artifacts.out/tapa.tar
          retention-days: 7
          compression-level: 9

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: /workspace/artifacts.out/tapa.tar
          body: |
            This is a staging build for ${{ github.sha }}.
          commit: ${{ github.sha }}
          name: Staging Build ${{ github.sha }}
          generateReleaseNotes: true
          prerelease: true
        if: "!github.event.act"
