# Copyright (c) 2024 RapidStream Design Automation, Inc. and contributors.
# All rights reserved. The contributor(s) of this file has/have agreed to the
# RapidStream Contributor License Agreement.

name: Staging Build

concurrency:
  group: release

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Staging Build
    runs-on: self-hosted

    steps:
      - name: Checkout myself
        uses: actions/checkout@v4

      - name: Run bazel
        uses: ./.github/actions/run-command
        with:
          run: |
            mkdir -p /workspace/artifacts.out/
            bazel build --config=release //:tapa-pkg-tar
            cp -L bazel-bin/tapa-pkg-tar.tar /workspace/artifacts.out/tapa.tar
            gzip /workspace/artifacts.out/tapa.tar
        env:
          UBUNTU_PRO_TOKEN: ${{ secrets.UBUNTU_PRO_TOKEN }}
          MAC_ADDRESS: ${{ secrets.MAC_ADDRESS }}

      - name: Upload artifacts
        # @v3 is kept for compatibility with the nektosact
        # Should be upgraded to @v4 when the nektosact is updated
        uses: actions/upload-artifact@v3
        with:
          name: tapa
          path: ${{ github.workspace }}/artifacts.out/tapa.tar.gz
          retention-days: 7

  test-staging:
    name: Test Staging Build
    runs-on: self-hosted
    needs: build

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-22
          - ubuntu-20
          - ubuntu-18
        xilinx_version:
          - "2024.1"
          - "2023.2"
          - "2023.1"
          - "2022.2"
          - "2022.1"

    steps:
      - name: Checkout myself
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: tapa

      - name: Run tests with the downloaded artifact
        uses: ./.github/actions/run-command
        with:
          run: |
            mkdir -p ~/.rapidstream-tapa/
            tar -xzf /workspace/tapa.tar.gz -C ~/.rapidstream-tapa/
            export RAPIDSTREAM_TAPA_HOME=~/.rapidstream-tapa
            source /opt/tools/xilinx/Vitis/${{ matrix.xilinx_version }}/settings64.sh
            bats tests/testsuite_self_test.bats
            find tests -name '*.bats' -print0 | xargs -0 bats
          imageTag: rapidstream/tapa-testenv:${{ matrix.os }}
          dockerfile: ./.github/docker/test-env/Dockerfile.${{ matrix.os }}
          context: ./.github/docker/test-env

  create-staging-release:
    name: Create Staging Release
    runs-on: self-hosted
    needs: test-staging
    if: "!github.event.act && startsWith(github.event.ref, 'refs/tags')"

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: tapa

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{ github.workspace }}/tapa.tar.gz
          body: |
            This is a staging build for ${{ github.sha }}.
          commit: ${{ github.sha }}
          name: Staging Build ${{ github.sha }}
          generateReleaseNotes: true
          prerelease: true
